# https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml
name: Publish Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: snok/install-poetry@v1
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        poetry install --no-interaction
    - name: Build package
      run: poetry build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      env:
        USERNAME: __token__
        PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry publish --username $USERNAME --password $PASSWORD